name = "Synthetic World"
author = "Sidpatchy"
version = "10.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "180096e4278cce36c182ce093692d8c786dee671c5f1e3c4199e3210ae9c20a2"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.84"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
